cd %1
R\bin\Rscript.exe -e "install.packages(c('R/colorspace_1.2-6.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/data.table_1.9.4.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/dichromat_2.0-0.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/digest_0.6.8.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/getopt_1.20.0.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/ggplot2_1.0.1.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/gtable_0.1.2.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/gWidgets_0.0-54.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/gWidgetstcltk_0.0-55.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/labeling_0.3.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/munsell_0.4.2.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/optparse_1.3.0.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/plyr_1.8.1.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/proto_0.3-10.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/RColorBrewer_1.1-2.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/reshape_0.8.5.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/reshape2_1.4.1.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/scales_0.2.4.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/stringr_0.6.2.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/tcltk2_1.2-11.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/tkrplot_0.0-23.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/Rcpp_0.11.5.zip'), repos=NULL)"
R\bin\Rscript.exe -e "install.packages(c('R/chron_2.3-45.zip'), repos=NULL)"


